### ISSUE TITLE
`auto_yaml` doesn't merge `.yaml` function tags properly

### ISSUE THREAD

**Issue by Arcensoth** [mcbeet/beet#204]
When `auto_yaml` (`beet.contrib.auto_yaml`) is enabled, `.yaml` function tags aren't merged properly and are instead replaced by one another.

Replacing the `.yaml` tags with `.json` equivalents solves the problem and the tags are merged as expected, hence why it is suspected that this has something to do with `auto_yaml`.

**Comment by vberlier** [comment]
Looks like this is an oversight in `beet.contrib.auto_yaml`, it's simply overwriting files instead of merging. This is fixed in `v0.50.5`.
