### ISSUE TITLE
Support for custom save locations

### ISSUE THREAD

**Issue by OrangeUtan** [mcbeet/beet#38]
`beet watch --link <World>` seems to .minecraft folder for saves.
My saves are however located in a custom location (the new Launcher supports that).

Is there an option to change the folder in which beet will look?

**Comment by vberlier** [comment]
When you use `beet link` or the `--link` option you can also give it the full path to your world folder. The following commands are equivalent:

```bash
$ beet link Demo
$ beet watch --link Demo
$ beet link C:\Users\name\AppData\Roaming\.minecraft\saves\Demo
$ beet watch --link C:\Users\name\AppData\Roaming\.minecraft\saves\Demo
```

**Comment by OrangeUtan** [comment]
Thx for the help. I watched your video again thats why I closed the issue already :D. But now its at least searchable for others :)
