### ISSUE TITLE
Toolchain docs don't exist (broken link)

### ISSUE THREAD

**Issue by penguinencounter** [mcbeet/beet#5]
In [README.md](https://github.com/vberlier/beet/blob/main/README.md), in the section **Toolchain**, there is a link to some documentation (goes to https://vberlier.github.io/beet/toolchain/) but that page doesn't exist.

**Comment by vberlier** [comment]
Yeah it's not quite there yet but I still prepared the link so I don't forget to do it. I'm keeping the issue open until the docs are up 👍

**Comment by vberlier** [comment]
The docs are now live at mcbeet.dev. Still a work-in-progress though.
