### ISSUE TITLE
Loading external data pack into a beet object says the content of all items in a data pack is None

### ISSUE THREAD

**Issue by DoubleF3lix** [mcbeet/beet#66]
Code to reproduce:
```py
pack_obj= beet.DataPack(path=...)
for name, file_instance in pack_obj.content:
  if isinstance(file_instance, beet.NamespaceFile):
    print(file_instance.content)
```
This will print `None` for every single file, even though this may not be the case.

**Comment by vberlier** [comment]
This is intended. File handles are lazy and you generally can't make any assumption about the `content` attribute. You can interact with files either through their serialized or deserialized representation. If you have no idea what kind of file you're interacting with you can use the generic `ensure_serialized()` or `ensure_deserialized()` methods no matter the state the file is currently in. If you're only working with text files you can use the equivalent `text` attribute. The type of the deserialized representation and the name of the attribute varies depending on the type of file. For example for json files the `data` attribute is equivalent to the `ensure_deserialized()` method. All of this is now explained in the [overview page](https://mcbeet.dev/overview/#file-handles) in the documentation.
